[package]
name = "MessageBoard"
version = "1.0.0"
authors = []

[addresses]
owner_addr = "cc12571f4aaa079f593acb4d2fed593c2a050642d2063e3bacad28549c89d6fb"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
